### ISSUE TITLE
SCRIPT NOT WORKING 

### ISSUE THREAD

**Issue by agentbugtracker** [NVISOsecurity/disable-flutter-tls-verification#1]
i really appreciate for making this script 
but this script is not working on my flutter app 
can please look into it 
error that showing is 

SM-G977N::com.app.com ]-> [+] libflutter.so loaded
[!] Flutter module not found.
[!] Flutter module not found.
i used this in arm7

link to my app
![Uploading Screenshot (4).png…]()
 [reacted]

**Comment by agentbugtracker** [comment]
i test in x64 
but i am getting following error

[+] Flutter library found
[!] ssl_verify_peer_cert not found. Please open an issue at https://github.com/NVISOsecurity/disable-flutter-tls-verification/issues

**Comment by TheDauntless** [comment]
It works for me on my Galaxy S10, though it does print an unnecessary error message:

```
(secenv) ➜  naughty frida -f com.h8.kcclsubscriber --codeshare TheDauntless/disable-flutter-tls-v1 -U --no-pause
     ____
    / _  |   Frida 15.1.28 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
Spawning `com.h8.kcclsubscriber`...                                     
[+] Java environment detected
Spawned `com.h8.kcclsubscriber`. Resuming main thread!                  
[SM G950F::com.h8.kcclsubscriber]-> [+] libflutter.so loaded
[+] Flutter library found
[!] ssl_verify_peer_cert not found. Please open an issue at https://github.com/NVISOsecurity/disable-flutter-tls-verification/issues
[+] ssl_verify_peer_cert found at offset: 0x5e8fc0

```

Make sure you use ProxyDroid and not the normal WIFI proxy settings since Flutter apps ignore the system proxy settings by default.

**Comment by agentbugtracker** [comment]
thanks for reply
i tried again but issue still there 
as you mentioned
ssl_verify_peer_cert found at offset: 0x5e8fc0
is not shown in my case

in my case 
[!] ssl_verify_peer_cert not found. Please open an issue at https://github.com/NVISOsecurity/disable-flutter-tls-verification/issues
 is shown 2 times

should i try with genymotion

**Comment by agentbugtracker** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/104664748/188780684-d82c21cf-9e0f-438a-b37c-f17d3611caff.png)
![Screenshot_20220907-084347_Droid Info](https://user-images.githubusercontent.com/104664748/188780704-8e5c3070-8a53-4b43-a98b-a19c3548deaf.jpg)
![Screenshot_20220907-084350_Droid Info](https://user-images.githubusercontent.com/104664748/188780712-149550e1-3827-44bf-8629-1917184ef63b.jpg)

**Comment by TheDauntless** [comment]
Can you try running the script and increasing the timeout on line 18 to 5000 ? 

And are you able to intercept the requests from the test app?

**Comment by agentbugtracker** [comment]
Very thanks for replying


 this script is working with your test app ,
but not working with my app even i increased timeout to 50000

i have attached ss
![Screenshot (12)](https://user-images.githubusercontent.com/104664748/188941705-80b5eca2-7f07-4c99-a4b1-4f95f98149c8.png)

**Comment by agentbugtracker** [comment]
i glad to say that i fixed the problem 
actually issue was with app 
i tried app from playstore 
but when i uninstalled the app and installed from apkcombo.com and tested that app
script works perfectly 
thank you for helping me and making this awesome script 
thankyou

**Comment by agentbugtracker** [comment]
hai today i tested this with another flutter app
script log shows that ssl_verify_peer_found 
but app doesnt not connect to internet and i donot see any logs in burp error section and nothing in proxy tab

i used python reflutter [https://github.com/Impact-I/reFlutter] for patching apk
i can only see images requests and other requests are not coming to my burp  

link to my app https://kgb-mpay.en.softonic.com/android

**Comment by TheDauntless** [comment]
These flutter binaries are now covered by my latest commit.

However, this app is using both Flutter and standard Java HTTPS libraries. If you run it with `objection --gadget=com.kgb.kgb_mbs explore --startup-command="android sslpinning disable"` you can see that at some point `TrustManagerImpl.checkTrustedRecursive()` is called.

This app is actually using the ssl_pinning_plugin which is a weirdly implemented SSL pinning library that asks Android to perform a pinning request. The way it's implemented, it's not straightforward to hook with Frida in a generic manner. In addition to that, it is also using an obfuscated okhttp2 library (see [this blog post](https://blog.nviso.eu/2019/04/02/circumventing-ssl-pinning-in-obfuscated-apps-with-okhttp/))

You can mitm by appending the following script to the disable-flutter-tls.js script:

```
Java.perform(function () {
  Java.use("c.h.a.a.a").b.overload("e.a.a.a.l", "e.a.a.a.n$d").implementation =
    function (lVar, dVar) {
      print("disable!");
      dVar.a("CONNECTION_SECURE");
    };

  let a = Java.use("g.g$a");
  a.a.overload("java.lang.String", "[Ljava.lang.String;").implementation =
    function (str, strArr) {
      return this;
    };
});
```
However, the app also has payload-level encryption so you'll need to reverse engineer it even further to figure out what is being sent back and forth. That is definitely outside of the scope of this project, so I'm closing this ticket, but thanks for sharing the sample.
