### ISSUE TITLE
Flutter module not found

### ISSUE THREAD

**Issue by alexispondo** [NVISOsecurity/disable-flutter-tls-verification#11]
Hello, after running my app i have this issue, can you help me to solve this ?
I use genymotion as emulator for Android 9 on Linux OS.
Frida server and client have a same version (16.0.15)

```
frida -U -f target.app --codeshare TheDauntless/disable-flutter-tls-v1`
     ____
    / _  |   Frida 16.0.15 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Nexus 4 (id=192.168.56.102:5555)
Spawning `target.app`...                                     
[+] Java environment detected
Spawned `target.app`. Resuming main thread!                  
[Nexus 4::target.app ]-> [+] libflutter.so loaded
[!] Flutter module not found.
```

**Comment by TheDauntless** [comment]
Can you share the application? If you can't, please share the md5sum of libflutter.so so that I can find another sample.

**Comment by victorQ8** [comment]
same issue
Spawning `com.target.app`...
[+] Java environment detected
Spawned `com.target.app`. Use %resume to let the main thread start executing!
[SM N9005::com.target.app]-> [!] Flutter module not found.

MD5 hash for armeabi-v7a of libflutter.so:
5f6a6c9668e393fe9fc6c2c9b0413785

MD5 hash for arm64-v8a of libflutter.so:
9d1e33101690c73666a72cccb1c5f482

**Comment by TheDauntless** [comment]
Can't troubleshoot without a test application. Please try the updated version of the script though, which should be more resilient.
