### ISSUE TITLE
X509: Certificate signed by unknown authority

### ISSUE THREAD

**Issue by palmmymumu** [NVISOsecurity/disable-flutter-tls-verification#12]
I used this script with demo app and everything works well but when I try it with my app it doesn't work.

`request GCM checkin: Post "https://android.clients.google.com'checkin": x509: certificate signed by unknown authority`

I proxied with ProxyDroids (iptables)

APK for test: https://drive.google.com/file/d/1cuqoP1tzr2YvOqrlpbw67eSXJK4VGfv0/view?usp=sharing
(It has 3 input fields you can test it with random number 10 & 13 & 6 digits)

**Comment by TheDauntless** [comment]
Sorry for the late reply, but it looks like this app is performing SSL pinning on top of the normal TLS verification, which is out of scope for this project.
