### ISSUE TITLE
library "libframework-connectivity-jni.so" not found

### ISSUE THREAD

**Issue by kenvin1508** [NVISOsecurity/disable-flutter-tls-verification#14]
`frida -U --codeshare TheDauntless/disable-flutter-tls-v1 -f eu.nviso.flutter_pinning`

[Android Emulator 5554::eu.nviso.flutter_pinning ]-> Error: java.lang.UnsatisfiedLinkError: dlopen failed: library "libframework-connectivity-jni.so" not found

I get an error when I run this cmd
Help me pls !

**Comment by TheDauntless** [comment]
This is a weird issue, and doesn't really seem related to Frida or the script. What kind of emulator are you using? (Are you using a 32bit x86 vm?)

Can you try on a different emulator or device?

**Comment by kriptogenic** [comment]
I'm also getting this error even in demo app. My device is rooted Pixel 7 with frida server 16.1.3

**Comment by kriptogenic** [comment]
I think this error causes because of overloading loadLibrary function. When I commented that lines, Demo app worked for me

**Comment by stevenking888** [comment]
I use android 13 redmi phone found the same error

**Comment by ttyA0** [comment]
> I think this error causes because of overloading loadLibrary function. When I commented that lines, Demo app worked for me

Thanks @kriptogenic ! This worked in my case as well. Specifically, I commented out line 49 of `disable-flutter-tls.js`.

```
// Check if Java environment is available (Android)
if (Java.available) {
    console.log("[+] Java environment detected");
    // Java.perform(hookSystemLoadLibrary);
```

However, I'm not very sure of any possible side-effect of not having this line. At least for now Frida and the demo app run normally without any error and I can see requests going through my Burp proxy.

**Comment by fellipgomes** [comment]
> > I think this error causes because of overloading loadLibrary function. When I commented that lines, Demo app worked for me
> 
> Thanks @kriptogenic ! This worked in my case as well. Specifically, I commented out line 49 of `disable-flutter-tls.js`.
> 
> ```
> // Check if Java environment is available (Android)
> if (Java.available) {
>     console.log("[+] Java environment detected");
>     // Java.perform(hookSystemLoadLibrary);
> ```
> 
> However, I'm not very sure of any possible side-effect of not having this line. At least for now Frida and the demo app run normally without any error and I can see requests going through my Burp proxy.

It worked, the code does not return an error, but it cannot intercept the network

**Comment by RJSDevel** [comment]
> > I think this error causes because of overloading loadLibrary function. When I commented that lines, Demo app worked for me
> 
> Thanks @kriptogenic ! This worked in my case as well. Specifically, I commented out line 49 of `disable-flutter-tls.js`.
> 
> ```
> // Check if Java environment is available (Android)
> if (Java.available) {
>     console.log("[+] Java environment detected");
>     // Java.perform(hookSystemLoadLibrary);
> ```
> 
> However, I'm not very sure of any possible side-effect of not having this line. At least for now Frida and the demo app run normally without any error and I can see requests going through my Burp proxy.

You've just disable everything

**Comment by 2shrestha22** [comment]
Any solution for this?

**Comment by hackure13** [comment]
Use the Android version prior 13

**Comment by TheDauntless** [comment]
I've pushed a new version that should fix this issue. Feel free to reopen if the problem persists.
