### ISSUE TITLE
library "libframework-connectivity-jni.so" not found

### ISSUE THREAD

**Issue by fellipgomes** [NVISOsecurity/disable-flutter-tls-verification#16]
pawned `com.nu.production`. Resuming main thread!                      
[SM G991B::com.nu.production ]-> Error: java.lang.UnsatisfiedLinkError: dlopen failed: library "libframework-connectivity-jni.so" not found
Process terminated
[SM G991B::com.nu.production ]->

App play store

https://play.google.com/store/apps/details?id=com.nu.production&hl=pt

**Comment by TheDauntless** [comment]
I've pushed a new version that should fix this issue. Feel free to reopen if the problem percists.
