### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by lv183037** [NVISOsecurity/disable-flutter-tls-verification#19]
I can't get Pinned Request when no agent is opened. The error information is as follows
12-20 17:37:11.414  3696  3724 I flutter : Request via DIO failed
12-20 17:37:11.414  3696  3724 I flutter : Exception: DioError [DioErrorType.other]: HandshakeException: Handshake error in client (OS Error:
12-20 17:37:11.414  3696  3724 I flutter :      CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393))
12-20 17:37:11.414  3696  3724 I flutter : Source stack:
12-20 17:37:11.414  3696  3724 I flutter : #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488)
12-20 17:37:11.414  3696  3724 I flutter : #1      DioMixin.request (package:dio/src/dio_mixin.dart:483)
12-20 17:37:11.414  3696  3724 I flutter : #2      DioMixin.get (package:dio/src/dio_mixin.dart:61)
12-20 17:37:11.414  3696  3724 I flutter : #3      _MyHomePageState.callPinnedHTTPS (package:flutter_pinning/main.dart:123)
12-20 17:37:11.414  3696  3724 I flutter : <asynchronous suspension>

**Comment by TheDauntless** [comment]
This is possibly related to the backend you are testing against and not necessarily the script/client. Can you share the test app? If so, please reopen the issue and link it.
