### ISSUE TITLE
Value never changing using frida (Interceptor.attach) is not being triggered

### ISSUE THREAD

**Issue by Alaa-HIjazi** [NVISOsecurity/disable-flutter-tls-verification#20]
Hello,

I was doing the same steps as the article and i got the offset from the library and hooked it via the js using frida.

However the interceptor.attach is never being triggered on the android and IOS devices changing the value of the function. 

Any idea why this is happening ?

It seems that the Interceptor.attach is not being triggered, i tried hooking other method and they return values.

**Comment by TheDauntless** [comment]
The current script doesn't use Interceptor.attach. Can you give a bit more info? Feels more like an issue with your setup than with the script.
