### ISSUE TITLE
Different end results on different apps, by returning 0 or 1

### ISSUE THREAD

**Issue by RahmatAliMalik5** [NVISOsecurity/disable-flutter-tls-verification#22]
Hi, Hope you are good.

I have just collected the SSL calls from the application successfully after the struggle of many many hours. Your script was working fine for the test application you provided and for [this](https://play.google.com/store/apps/details?id=com.latroservices.markettracker&pcampaignid=web_share) application. But was not working fine for [this](https://play.google.com/store/apps/details?id=com.application.bficgold&pcampaignid=web_share) application which was just updated on Feb 26, 2024, and this was my target application.

By updating the return type from 0 to 1, the application started to work fine and SSL calls can be accessed. Writing here so, one can be able to find the solution if needed.

https://github.com/NVISOsecurity/disable-flutter-tls-verification/blob/d3ae368f1295044dee7795948ed94940458138a6/disable-flutter-tls.js#L139-L143

**Comment by TheDauntless** [comment]
I just tested the updated version of the script on the BFICGold application and it seems to be working. Changing the return value in that function to 1 is unlikely to work though. Feel free to reopen in case you still have issues.
