### ISSUE TITLE
Flutter App not working

### ISSUE THREAD

**Issue by fellipgomes** [NVISOsecurity/disable-flutter-tls-verification#25]
Hello

This banking app uses Flutter. I tried several ways, including using your script to bypass pinning, but nothing worked.

Is there any solution to be able to intercept HTTP traffic from flutter applications? From what I understand, Flutter has its own list of certificates and does not use the one provided by Android.

https://play.google.com/store/apps/details?id=com.nu.production&hl=en_US

**Comment by TheDauntless** [comment]
This app uses multiple HTTP libraries.

Combine the script from this repo with (eg)[ frida-multiple-unpinning](https://codeshare.frida.re/@akabe1/frida-multiple-unpinning/) and you will at least see the first request:

![image](https://github.com/NVISOsecurity/disable-flutter-tls-verification/assets/1650034/f607b5ef-d6da-4833-a0b3-11b6ee318b0e)
