### ISSUE TITLE
Flutter library not found but shows ssl_verify_peer_cert has been patched. But it still not working

### ISSUE THREAD

**Issue by bopotato0223** [NVISOsecurity/disable-flutter-tls-verification#26]
Here are my device specifications:
Nox Emulator running x86_64
frida-server-16.2.1-android-x86_64  --> this is the one i uploaded on the mobile device
Frida 16.2.1 --> this is the one running on my laptop

Software installed:
Proxydroid
pinning.apk

I am trying to ssl bypass the example app in this github (pinning.apk) but I always get this message:

```
Spawning `eu.nviso.flutter_pinning`...
[+] Attempting to find and hook ssl_verify_peer_cert (1/5)
[!] Flutter library not found
Spawned `eu.nviso.flutter_pinning`. Resuming main thread!
[SM-G965N::eu.nviso.flutter_pinning ]-> [+] Attempting to find and hook ssl_verify_peer_cert (2/5)
[+] ssl_verify_peer_cert found at offset: 0x3faec6
[+] ssl_verify_peer_cert has been patched
```

It says it can't find the flutter library.
I tried to change timeout value but it still not working

Now to check if flutter is really not in there I used this code.
```
function hook_ssl_verify_result(address)
{
  Interceptor.attach(address, {
    onEnter: function(args) {
      console.log("Disabling SSL validation")
    },
    onLeave: function(retval)
    {
      console.log("Retval: " + retval)
      retval.replace(0x1);
  
    }
  });
}




function disablePinning(){
    // Change the offset on the line below with the binwalk result
    // If you are on 32 bit, add 1 to the offset to indicate it is a THUMB function: .add(0x1)
    // Otherwise, you will get  'Error: unable to intercept function at ......; please file a bug'
    var address_flutter = Module.findBaseAddress('libflutter.so')
    var address = Module.findBaseAddress('libflutter.so').add(0x60E71)
    console.log(address_flutter)
    hook_ssl_verify_result(address);
}
setTimeout(disablePinning, 9000)



function disablePinning(){
    // Change the offset on the line below with the binwalk result
    // If you are on 32 bit, add 1 to the offset to indicate it is a THUMB function: .add(0x1)
    // Otherwise, you will get  'Error: unable to intercept function at ......; please file a bug'
    var address_flutter = Module.findBaseAddress('libflutter.so')
    var address = Module.findBaseAddress('libflutter.so').add(0x60E71)
    console.log(address_flutter)
    hook_ssl_verify_result(address);
}
setTimeout(disablePinning, 9000)
```
The result is:
Spawned `eu.nviso.flutter_pinning`. Resuming main thread!
[SM-G965N::eu.nviso.flutter_pinning ]-> 0x70abe0e42000

It was able to find libflutter.so because it returned its address  0x70abe0e42000. However it just stop there. From the looks of it, the function hook_ssl_verify_result did not execute. 

Am I missing something?

Could it be the frida versions that I am using?

May I know the frida versions that you used in the blog?

**Comment by TheDauntless** [comment]
Everything looks fine here. It only says that it can't find the library in the first pass (1/5) because the app hasn't initialized yet and the libflutter.so library hasn't been loaded yet. On the second pass (2/5) it does find the correct offset.

Frida version should be irrelevant, I always just use the latest version.

Are you seeing the HTTP flow in your proxy? The only thing I can imagine is that your proxy is misconfigured and that it never even succeeds in building a TLS connection. Note that the app will say 'mitm detected' even if it can't connect to the server at all.

Please follow this checklist to make sure your proxy is set up correctly: https://blog.nviso.eu/2020/11/19/proxying-android-app-traffic-common-issues-checklist/

**Comment by bopotato0223** [comment]
Thanks for the list. I'll get back to you after getting through out the list

**Comment by bopotato0223** [comment]
It works. I made a few errors. The link you gave me was very helpful. Thank you
