### ISSUE TITLE
Flutter library found, but ssl_verify_peer_cert could not be found

### ISSUE THREAD

**Issue by william-beaux** [NVISOsecurity/disable-flutter-tls-verification#28]
iOS [app](https://apps.apple.com/fi/app/instafollow-follower-reports/id1597994653) - the md5sum b547eba74d755c423d83341d3cb4306a for '/Payload/Runner.app/Frameworks/Flutter.framework/Flutter' is not present in the samples folder.

**Comment by william-beaux** [comment]
Using Ghidra to look for "x509.cc" and 0x186 (scalar) yielded the following pattern:

EF 3B B6 6D ED 33 01 6D EB 2B 02 6D E9 23 03 6D FC 6F 04 A9 FA 67 05 A9 F8 5F 06 A9 F6 57 07 A9 F4 4F 08 A9 FD 7B 09 A9 FD 43 02 91 FF C3 09 D1

However, it hooks multiple instances. 

![Screenshot 2024-06-03 at 3 32 23 PM](https://github.com/NVISOsecurity/disable-flutter-tls-verification/assets/171373097/742b470d-91e8-4ea8-8f49-c55e76416749)

**Comment by william-beaux** [comment]
@TheDauntless attached
[InstaFollow_99053.ipa.zip](https://github.com/user-attachments/files/16270598/InstaFollow_99053.ipa.zip)

**Comment by william-beaux** [comment]
@TheDauntless - attached - looks like BoringSSL updated their library 

[ipa.zip](https://github.com/user-attachments/files/16270632/ipa.zip)

**Comment by TheDauntless** [comment]
@william-beaux I've added a pattern and it seems to be working on the app (I don't have an IG account to verify but I can intercept the ad requests). Can you verify please?

**Comment by TheDauntless** [comment]
@cloud-jie  If you can share the APK or a URL I can make sure this tool works on your version as well :)

**Comment by william-beaux** [comment]
> @william-beaux I've added a pattern and it seems to be working on the app (I don't have an IG account to verify but I can intercept the ad requests). Can you verify please?

Resolved.
