### ISSUE TITLE
Not working for a specific app I have

### ISSUE THREAD

**Issue by tcortega** [NVISOsecurity/disable-flutter-tls-verification#32]
I've been using this scripts for other apps and it works great, but I faced an issue when attempting to use it for `com.foodtosave.foodtosave`.

Inside the application, when attempting to make any requests, I get the following error toast:
`HandshakeException: Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: Invalid certificate verification context(handshake.cc:393))`

Here are the frida logs:
```
     ____
    / _  |   Frida 16.3.3 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to SM N975F (id=127.0.0.1:21503)
Spawning `com.foodtosave.foodtosave`...
[+] Attempting to find and hook ssl_verify_peer_cert (1/5)
[!] Flutter library not found
Spawned `com.foodtosave.foodtosave`. Resuming main thread!
[SM N975F::com.foodtosave.foodtosave ]-> [+] Attempting to find and hook ssl_verify_peer_cert (2/5)
[+] ssl_verify_peer_cert found at offset: 0x78f0ee
[+] ssl_verify_peer_cert has been patched
```

**Comment by tcortega** [comment]
In case the package name is not enough, here is the test application: https://play.google.com/store/apps/details?id=com.foodtosave.foodtosave&hl=en

**Comment by tcortega** [comment]
Apparently the example `pinning.apk` that is in the repository isn't working either, but it doesn't seem to be related at all to the issue I am facing above.
```
scott@DESKTOP-TOR4F8E:~/frida$ frida -U -l flutter.js -f eu.nviso.flutter_pinning
     ____
    / _  |   Frida 16.3.3 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to SM N975F (id=127.0.0.1:21503)
Spawning `eu.nviso.flutter_pinning`...
[+] Attempting to find and hook ssl_verify_peer_cert (1/5)
[!] Flutter library not found
Spawned `eu.nviso.flutter_pinning`. Resuming main thread!
[SM N975F::eu.nviso.flutter_pinning ]-> [+] Attempting to find and hook ssl_verify_peer_cert (2/5)
[!] Flutter library not found
[+] Attempting to find and hook ssl_verify_peer_cert (3/5)
[!] Flutter library not found
[+] Attempting to find and hook ssl_verify_peer_cert (4/5)
[!] Flutter library not found
[+] Attempting to find and hook ssl_verify_peer_cert (5/5)
[!] Flutter library not found
[!] Max attempts reached, stopping
```

**Comment by TheDauntless** [comment]
@tcortega this is weird, because it works on my phone:

```
(secenv) ➜  test_app git:(dev) ✗ frida -U -f com.foodtosave.foodtosave  -l ../disable-flutter-tls.js
     ____
    / _  |   Frida 16.3.3 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to SM G950F (id=ce02171255925c1b04)
Spawning `com.foodtosave.foodtosave`...                                 
[+] Attempting to find and hook ssl_verify_peer_cert (1/5)
[!] Flutter library not found
Spawned `com.foodtosave.foodtosave`. Resuming main thread!              
[SM G950F::com.foodtosave.foodtosave ]-> [+] Attempting to find and hook ssl_verify_peer_cert (2/5)
[+] ssl_verify_peer_cert found at offset: 0x6c3084
[+] ssl_verify_peer_cert has been patched
```

The offset is different though. Maybe they updated the app just now? It looks like you're using a Galaxy note, which should be ARM64, just like my S8.

I also see the request (fake data):

![image](https://github.com/user-attachments/assets/ff5da395-8ca2-4894-a888-140d68ca448c)

The pinning app also works on my S8:
```
frida -U -f eu.nviso.flutter_pinning -l ../disable-flutter-tls.js
     ____
    / _  |   Frida 16.3.3 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to SM G950F (id=ce02171255925c1b04)
Spawning `eu.nviso.flutter_pinning`...                                  
[+] Attempting to find and hook ssl_verify_peer_cert (1/5)
[!] Flutter library not found
Spawned `eu.nviso.flutter_pinning`. Resuming main thread!               
[SM G950F::eu.nviso.flutter_pinning ]-> [+] Attempting to find and hook ssl_verify_peer_cert (2/5)
[+] ssl_verify_peer_cert found at offset: 0x3a251c
[+] ssl_verify_peer_cert has been patched
[SM G950F::eu.nviso.flutter_pinning ]->                                                                                                                                                                                          
[SM G950F::eu.nviso.flutter_pinning ]-> exit
^[[A^[[A
Thank you for using Frida!
```

**Comment by tcortega** [comment]
> @tcortega this is weird, because it works on my phone:
> 
> ```
> (secenv) ➜  test_app git:(dev) ✗ frida -U -f com.foodtosave.foodtosave  -l ../disable-flutter-tls.js
>      ____
>     / _  |   Frida 16.3.3 - A world-class dynamic instrumentation toolkit
>    | (_| |
>     > _  |   Commands:
>    /_/ |_|       help      -> Displays the help system
>    . . . .       object?   -> Display information about 'object'
>    . . . .       exit/quit -> Exit
>    . . . .
>    . . . .   More info at https://frida.re/docs/home/
>    . . . .
>    . . . .   Connected to SM G950F (id=ce02171255925c1b04)
> Spawning `com.foodtosave.foodtosave`...                                 
> [+] Attempting to find and hook ssl_verify_peer_cert (1/5)
> [!] Flutter library not found
> Spawned `com.foodtosave.foodtosave`. Resuming main thread!              
> [SM G950F::com.foodtosave.foodtosave ]-> [+] Attempting to find and hook ssl_verify_peer_cert (2/5)
> [+] ssl_verify_peer_cert found at offset: 0x6c3084
> [+] ssl_verify_peer_cert has been patched
> ```
> 
> The offset is different though. Maybe they updated the app just now? It looks like you're using a Galaxy note, which should be ARM64, just like my S8.
> 
> I also see the request (fake data):
> 
> ![image](https://private-user-images.githubusercontent.com/1650034/357353951-ff5da395-8ca2-4894-a888-140d68ca448c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDE0NDAsIm5iZiI6MTcyMzYwMTE0MCwicGF0aCI6Ii8xNjUwMDM0LzM1NzM1Mzk1MS1mZjVkYTM5NS04Y2EyLTQ4OTQtYTg4OC0xNDBkNjhjYTQ0OGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTRUMDIwNTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWNjNTE4OTdjYzM0N2NiODEwOWZlNWE3Mjg4NDQwNjliZTg1OGI0YjI0ODkyYTEwYzQ4YWQ3ZTMyZDdmNWE3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sT669e03eEBPXlKVaVOmyH9NcY_cRXv8aGVH802GlBU)
> 
> The pinning app also works on my S8:
> 
> ```
> frida -U -f eu.nviso.flutter_pinning -l ../disable-flutter-tls.js
>      ____
>     / _  |   Frida 16.3.3 - A world-class dynamic instrumentation toolkit
>    | (_| |
>     > _  |   Commands:
>    /_/ |_|       help      -> Displays the help system
>    . . . .       object?   -> Display information about 'object'
>    . . . .       exit/quit -> Exit
>    . . . .
>    . . . .   More info at https://frida.re/docs/home/
>    . . . .
>    . . . .   Connected to SM G950F (id=ce02171255925c1b04)
> Spawning `eu.nviso.flutter_pinning`...                                  
> [+] Attempting to find and hook ssl_verify_peer_cert (1/5)
> [!] Flutter library not found
> Spawned `eu.nviso.flutter_pinning`. Resuming main thread!               
> [SM G950F::eu.nviso.flutter_pinning ]-> [+] Attempting to find and hook ssl_verify_peer_cert (2/5)
> [+] ssl_verify_peer_cert found at offset: 0x3a251c
> [+] ssl_verify_peer_cert has been patched
> [SM G950F::eu.nviso.flutter_pinning ]->                                                                                                                                                                                          
> [SM G950F::eu.nviso.flutter_pinning ]-> exit
> ^[[A^[[A
> Thank you for using Frida!
> ```

Weird. I was trying it on an emulator, sadly I don't got an android phone on my reach anymore. I'll try resetting the emulator.

**Comment by TheDauntless** [comment]
I tested it on an emulator too, and it worked:
```
frida --codeshare TheDauntless/disable-flutter-tls-v1 -F -U
     ____
    / _  |   Frida 16.4.8 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Android Emulator 5554 (id=emulator-5554)
Hello! This is the first time you're running this particular snippet, or the snippet's source code has changed.

Project Name: disable-flutter-tls-v1
Author: @TheDauntless
Slug: TheDauntless/disable-flutter-tls-v1
Fingerprint: 84a6b40b4b868cdbb6767b71b5f6d633d9aa40d0f6cb3e0ff9ad0ad278d72140
URL: https://codeshare.frida.re/@TheDauntless/disable-flutter-tls-v1

Are you sure you'd like to trust this project? [y/N] y
Adding fingerprint 84a6b40b4b868cdbb6767b71b5f6d633d9aa40d0f6cb3e0ff9ad0ad278d72140 to the trust store! You won't be prompted again unless the code changes.
[+] Arch: x64
[+] Attempting to find and hook ssl_verify_peer_cert (1/5)
[+] ssl_verify_peer_cert found at offset: 0x78f0ee
[+] ssl_verify_peer_cert has been patched
[Android Emulator 5554::Food To Save ]-> exit
```

**Comment by TheDauntless** [comment]
@Stephenmiles08  Please open a separate issue.

To help you get started:
* ProxyDroid is open source, so you can build it for x64
* ProxyDroid uses iptables, which may or may not work on your x64 emulator. It really is emulator specific. Look up the different proxy configurations for your specific emulator to see which one is usable. Alternatively, you can intercept using a vpn, rogue wifi network, DNS mitm, ...
* You can also try out https://github.com/Impact-I/reFlutter

**Comment by tcortega** [comment]
@TheDauntless I tried it again, using an amd64 physical device, with no success. It captures browser data, however, it doesn't seem like the app chose to use the proxy at all, and when I force it to use the proxy, the app simply doesn't open, which means that apparently the flutter hook is not working? Not sure if it might be because of Fiddler, but I will give burp suite a try.

**Comment by tcortega** [comment]
@TheDauntless Honestly, I have absolutely no idea on why it isn't working on my end. As it appears that it is properly patching the ssl_verify_peer_cert.

```
     ____
    / _  |   Frida 16.3.3 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Redmi Note 9S (id=7ca1e28e)
Spawning `com.foodtosave.foodtosave`...                                 

== Redirecting all TCP connections to 192.168.100.42:8888 ==
== Hooked native TLS lib libssl.so ==
[+] Attempting to find and hook ssl_verify_peer_cert (1/5)
[!] Flutter library not found
Spawned `com.foodtosave.foodtosave`. Resuming main thread!              
[Redmi Note 9S::com.foodtosave.foodtosave ]-> == Proxy system configuration overridden to 192.168.100.42:8888 ==
== Proxy configuration overridden to 192.168.100.42:8888 ==
== System certificate trust injected ==
== Certificate unpinning completed ==
== Unpinning fallback auto-patcher installed ==
[+] Attempting to find and hook ssl_verify_peer_cert (2/5)
[+] ssl_verify_peer_cert found at offset: 0x6c3084
[+] ssl_verify_peer_cert has been patched
Manually intercepting connection to [28:0:3:f0:40:4:8:6:0:0:0:0:0:0:20:3]:443
Manually intercepting connection to ::ffff:142.251.135.35:443
```

**Comment by tcortega** [comment]
Nevermind, got it figured out on my end. Apparently I have an issue in one of my frida scripts from httptoolkit's repo that interfered with it.
