### ISSUE TITLE
Off Topic/Help: Unable to intercept requests of a Java mobile game

### ISSUE THREAD

**Issue by delasy** [NVISOsecurity/disable-flutter-tls-verification#33]
I'm sorry for off-topic, I know this is not related to this project at all. I'm desperate and have no idea where I can ask about this. I learned to use Burp + NoPE from [this video](https://youtu.be/x6yHbCON1u8) of yours, thought you might help if you are have time.

**The Problem**: \
I'm trying to intercept requests of iOS mobile game specifically [this one](https://apps.apple.com/app/stone-age-survival-settlement/id6450828603). on Android emulator I have no problem intercepting, but when it comes to iOS I use Burp + NoPE on a palera1n jailbroken iPhone with Frida and objection `ios sslpinning disable` and I still can't intercept the needed request, specifically I want to intercept `api dot gamepromo dot io` . I disassembled the application, found that it actually doing this request but in Burp it doesn't show. the only thing that shows is the error message in log "The client failed to negotiate a TLS connection to {host}:443: Remote host terminated the handshake" (and I have all the certificates installed and trusted :).

What I tried:
1. Burp + NoPE
2. Reqable (doesn't show at all)
3. Proxyman (doesn't show at all)
4. HTTP Toolkit (aborted connection to X)
5. https://codeshare.frida.re/@thedauntless/disable-flutter-tls-v1/
6. https://codeshare.frida.re/@federicodotta/ios13-pinning-bypass/
7. https://codeshare.frida.re/@snooze6/ios-pinning-disable/
8. https://codeshare.frida.re/@electrondefuser/ios-proxy-detection-bypass/
9. objection `ios sslpinning disable`
10. Tested with DVIA-v2 and I was able to intercept all NLS requests except App Transport Security.

the only thing that seems to be super strange is that on Android it's sending user-agent "Dalvik/2.1.0 (Linux; U; Android 12; ...)". From the error that I see I believe the problem could be that certificate that I'm sending to end server is rejected during handshake? I honestly have no idea what the problem is and how I could solve it.

I would appreciate any help 🙏

**Comment by delasy** [comment]
I tried `rvictl -s` and `tcpdump -i rvi0 -w capture.pcap -P` with https://codeshare.frida.re/@jankais3r/ios-15-tls-keylogger/ \
I got the packets but packets to this host are not decrypted for some reason (for other hosts are decrypted):

![image](https://github.com/user-attachments/assets/03be37e3-c6ec-4cbf-af04-e6d85a6b8503)

**Comment by delasy** [comment]
I found a way to intercept requests now

**Comment by delasy** [comment]
@Geczy  I disassembled the iOS game and replaced the request URL with a custom URL of the same length (<- important), which pointed to my self-hosted endpoint. Then I reassembled the game and signed it with my own keys. The key here is that my url was actually a Node.js application that was dumping all incoming requests into server log.

**Comment by Geczy** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/1036968?v=4&amp;size=80">@Geczy](https://github.com/Geczy?rgh-link-date=2025-01-26T19%3A07%3A00.000Z) I disassembled the iOS game and replaced the request URL with a custom URL of the same length (<- important), which pointed to my self-hosted endpoint. Then I reassembled the game and signed it with my own keys. The key here is that my url was actually a Node.js application that was dumping all incoming requests into server log.

Nice seems like that could work, what app did you use to replace the url and rebuild it? 
Can you share your node js script? I'm thinking maybe [httpbin](https://github.com/postmanlabs/httpbin) could help

I have a decrypted ipa file and can load it with Trollstore

**Comment by delasy** [comment]
> Nice seems like that could work, what app did you use to replace the url and rebuild it? Can you share your node js script? I'm thinking maybe [httpbin](https://github.com/postmanlabs/httpbin) could help
> 
> I have a decrypted ipa file and can load it with Trollstore

I used Hopper for disassembling and here's my code snippet: https://gist.github.com/delasy/318f6511beb00efb5b3a19c504131a2f

I used free trial on Hopper though which doesn't allow editing binary, so instead I was actually using HexEd.it website to find position in the binary and replacing it with custom endpoint url.

**Comment by Geczy** [comment]
Thanks, I got all requests logged doing this method. I don't know how this app does it, but anytime I try to log the request and then repeat it, their backend api responds with a json "Error: missing resource"

But if I turn off all logging, or turn off proxies, and use their untouched app the requests work fine
